LOG_FUNC_ENTRY  main.cpp main() line 11: ThreadId = 140708905457472
LOG_FUNC_ENTRY  main.cpp main_th() line 53: ThreadId = 140708879718144
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708879718144
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708879718144
LOG_FUNC_ENTRY  main.cpp main_th() line 53: ThreadId = 140708888110848
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708888110848
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708888110848
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708879718144
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708879718144
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708888110848
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708888110848
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708879718144
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708879718144
LOG_FUNC_ENTRY  main.cpp test2() line 46: ThreadId = 140708888110848
LOG_FUNC_EXIT   main.cpp test2() line 48: ThreadId = 140708888110848
LOG_FUNC_EXIT   main.cpp main_th() line 62: ThreadId = 140708879718144
LOG_FUNC_EXIT   main.cpp main_th() line 62: ThreadId = 140708888110848
LOG_INFO        main.cpp main() line 19: Test Info 1
LOG_WARNING     main.cpp main() line 20: Test Warning 2
LOG_ERROR       main.cpp main() line 21: Test Error 3
LOG_DEBUG       main.cpp main() line 22: Test Debug 4
LOG_FUNC_ENTRY  main.cpp test1() line 39: ThreadId = 140708905457472
LOG_FUNC_EXIT   main.cpp test1() line 41: ThreadId = 140708905457472
LOG_FUNC_ENTRY  main.cpp test1() line 39: ThreadId = 140708905457472
LOG_FUNC_EXIT   main.cpp test1() line 41: ThreadId = 140708905457472
LOG_FUNC_ENTRY  main.cpp test1() line 39: ThreadId = 140708905457472
LOG_FUNC_EXIT   main.cpp test1() line 41: ThreadId = 140708905457472
LOG_FUNC_EXIT   main.cpp main() line 34: ThreadId = 140708905457472
